apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui-service
  namespace: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins-master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http