apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configmap
  namespace: application
data:
  REPLICA: "rs0"
  BE_PORT: "3000"
  DB_HOST: "localhost"
  DB_PORT: "27018"
  DB_NAME: "finalProj"
  ME_PORT: "8081"
