apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: nexus-pull-secret
      containers:
        - name: backend
          image: nexus.local/be-img:46
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
          - secretRef:
              name: back-env-secret
          - configMapRef:
              name: backend-configmap