apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      imagePullSecrets:
        - name: nexus-pull-secret
      containers:
        - name: mongo-express
          image: nexus.local/mongo-express:1.0.2
          ports:
            - containerPort: 8081
          env:            
            - name: MONGODB_SERVER
              value: "mongodb-service"
            - name: MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodb-service"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ROOT_NAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ROOT_PASS
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ME_AUTH_UNAME
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ME_AUTH_UPASS