apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: database
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      imagePullSecrets:
        - name: nexus-pull-secret
      containers:
        - name: mongodb
          image: nexus.local/mongo:8
          ports:
            - containerPort: 27017
          command:
            - "mongod"
            - "--port"
            - "$(DB_PORT)"
            - "--bind_ip_all"
            - "--replSet=rs0"
          env:
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: DB_PORT
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ROOT_NAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ROOT_PASS
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Mi