apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: application
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: nexus-pull-secret
      containers:
        - name: frontend
          image: nexus.local/fe-img:latest
          ports:
            - containerPort: 80
