apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-fluentbit
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      serviceAccountName: log-fluentbit-sa
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:3.1.9
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: log-fluentbit-config