apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.19.18
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://log-elasticsearch-service:9200"
          ports:
            - containerPort: 5601