apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: application
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27018
          command:
            - "mongod"
            - "--port"
            - "$(DB_PORT)"
          env:
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: application-configmap
                  key: DB_PORT
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ROOT_NAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-auth
                  key: ROOT_PASS
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Mi