pipeline {
    agent {
        kubernetes {
            cloud 'kubernetes-cloud'
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ['cat']
    tty: true
    volumeMounts:
    - name: registry-creds
      mountPath: /kaniko/.docker
  volumes:
  - name: registry-creds
    secret:
      secretName: kaniko-nexus-secret
      items:
      - key: .dockerconfigjson
        path: config.json
'''
        }
    }
    stages {
        stage('Build and Push Backend') {
            steps {
                container('kaniko') {
                    sh '/kaniko/executor --context=dir://./backend-repo --dockerfile=./backend-repo/Dockerfile --destination=nexus-service.nexus.svc.cluster.local:8081/be-img:${BUILD_NUMBER} --destination=nexus-service.nexus.svc.cluster.local:8081/be-img:latest --insecure'
                }
            }
        }
    }
}