apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "${JENKINS_ADMIN_ID}"
              password: "${JENKINS_ADMIN_PASSWORD}"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      numExecutors: 0